export const tokenToSemantic: {} = {
  /* PaletteBackgroundColors & PaletteTextColors */

  background: 'surfacesPrimary',
  bodyStandoutBackground: 'surfacesSecondary',
  bodyFrameBackground: 'surfacesTertiary',
  bodyFrameDivider: 'dividersSecondary',
  bodyText: 'textPrimary',
  bodyTextChecked: 'gray950',
  subText: 'textSecondary',
  bodyDivider: 'dividersPrimary',

  disabledBackground: 'surfacesTertiary',
  disabledText: 'textDisabledHighContrast',
  disabledBodyText: 'textDisabled',
  disabledSubtext: 'gray200',
  disabledBodySubtext: 'gray300',

  focusBorder: 'transparent',
  variantBorder: 'transparent',
  variantBorderHovered: 'transparent',
  defaultStateBackground: 'transparent',

  errorText: 'dangerPrimary',
  warningText: 'warningPrimary',
  errorBackground: 'dangerTint10',
  blockingBackground: 'dangerTint10',
  warningBackground: 'warningPrimary',
  warningHighlight: 'warningTint10',
  successBackground: 'successTint10',

  inputBorder: 'transparent',
  inputBorderHovered: 'transparent',
  inputBackground: 'transparent',
  inputBackgroundChecked: 'transparent',
  inputBackgroundCheckedHovered: 'transparent',
  inputForegroundChecked: 'communicationBlue',
  inputFocusBorderAlt: 'transparent',
  smallInputBorder: 'transparent',
  inputText: 'textPrimary',
  inputTextHovered: 'textPrimary',
  inputPlaceholderText: 'textSecondary',

  buttonBackgroundChecked: 'buttonBackground',
  buttonBackgroundHovered: 'buttonBackground',
  buttonBackgroundCheckedHovered: 'buttonBackground',
  buttonBackgroundPressed: 'buttonBackgroundPressed',
  buttonBackgroundDisabled: 'buttonBackgroundDisabled',
  buttonText: 'textOnAccent',
  buttonTextHovered: '#ffffff',
  buttonTextChecked: '#ffffff',
  buttonTextCheckedHovered: '#ffffff',
  buttonTextPressed: 'textOnAccent',
  buttonTextDisabled: 'buttonTextDisabled',
  buttonBorderDisabled: 'transparent',
  buttonBorderFocused: 'transparent',

  primaryButtonBackground: 'buttonBackground',
  primaryButtonBackgroundHovered: 'buttonBackground',
  primaryButtonBackgroundPressed: 'buttonBackgroundPressed',
  primaryButtonBackgroundDisabled: 'buttonBackgroundDisabled',
  primaryButtonBorder: 'transparent',
  primaryButtonBorderFocused: 'transparent',
  primaryButtonText: 'textOnAccent',
  primaryButtonTextHovered: '#ffffff',
  primaryButtonTextPressed: '#ffffff',
  primaryButtonTextDisabled: 'buttonTextDisabled',

  accentButtonBackground: 'buttonBackground',
  accentButtonText: 'textOnAccent',

  menuBackground: 'menuBackground',
  menuDivider: 'transparent',
  menuIcon: 'menuIcon',
  menuHeader: 'transparent',
  menuItemBackgroundHovered: 'transparent',
  menuItemBackgroundPressed: 'transparent',
  menuItemText: 'menuItemText',
  menuItemTextHovered: 'gray900',

  listBackground: 'listBackground',
  listText: 'menuItemText',
  listItemBackgroundHovered: 'transparent',
  listItemBackgroundChecked: 'transparent',
  listItemBackgroundCheckedHovered: 'transparent',

  listHeaderBackgroundHovered: 'transparent',
  listHeaderBackgroundPressed: 'transparent',

  actionLink: 'textPrimary',
  actionLinkHovered: 'textPrimary',
  link: 'textHyperLink',
  linkHovered: 'textHyperLink',
  linkPressed: 'textHyperLink',

  /* ControlColorTokens */

  buttonBackground: 'buttonBackground',
  buttonBorder: 'transparent',
  buttonContent: 'textPrimary',
  buttonIcon: 'iconsSecondary',

  buttonPressedBackground: 'buttonBackgroundPressed',
  buttonPressedBorder: 'transparent',
  buttonPressedContent: 'textOnAccent',
  buttonPressedIcon: 'iconsOnAccent',

  buttonDisabledBackground: 'buttonBackgroundDisabled',
  buttonDisabledBorder: 'transparent',
  buttonDisabledContent: 'buttonTextDisabled',
  buttonDisabledIcon: 'buttonTextDisabled',

  ghostBackground: 'transparent',
  ghostBorder: 'transparent',
  ghostContent: 'textDominant',
  ghostIcon: 'textDominant',

  ghostHoveredBackground: 'transparent',
  ghostHoveredBorder: 'transparent',
  ghostHoveredContent: 'textDominant',
  ghostHoveredIcon: 'textDominant',

  ghostFocusedBackground: 'transparent',
  ghostFocusedBorder: 'transparent',
  ghostFocusedContent: 'textDominant',
  ghostFocusedIcon: 'textDominant',

  ghostPressedBackground: 'transparent',
  ghostPressedBorder: 'transparent',
  ghostPressedContent: 'communicationBlueTint20',
  ghostPressedIcon: 'communicationBlueTint20',

  ghostDisabledBackground: 'transparent',
  ghostDisabledBorder: 'transparent',
  ghostDisabledContent: 'iconsDisabled',
  ghostDisabledIcon: 'iconsDisabled',

  brandBackground: 'communicationBlue',
  brandBorder: 'transparent',
  brandContent: 'textDominant',
  brandIcon: 'textDominant',

  brandHoveredBackground: 'communicationBlue',
  brandHoveredBorder: 'transparent',
  brandHoveredContent: 'textDominant',
  brandHoveredIcon: 'textDominant',

  brandFocusedBackground: 'communicationBlue',
  brandFocusedBorder: 'transparent',
  brandFocusedContent: 'textDominant',
  brandFocusedIcon: 'textDominant',

  brandPressedBackground: 'communicationBlueTint10',
  brandPressedBorder: 'transparent',
  brandPressedContent: 'textDominant',
  brandPressedIcon: 'textDominant',

  brandDisabledBackground: 'gray100',
  brandDisabledBorder: 'transparent',
  brandDisabledContent: 'textDisabled',
  brandDisabledIcon: 'textDisabled',

  buttonCheckedBackground: 'communicationBlueTint10',
  buttonCheckedContent: 'textDominant',
  buttonCheckedHoveredBackground: 'communicationBlueTint10',
  buttonCheckedHoveredContent: 'textDominant',

  brandCheckedBackground: 'communicationBlueTint10',
  brandCheckedContent: 'textDominant',
  brandCheckedHoveredBackground: 'communicationBlueTint10',
  brandCheckedHoveredContent: 'textDominant',

  ghostCheckedBackground: 'transparent',
  ghostCheckedContent: 'communicationBlueTint20',
  ghostCheckedHoveredBackground: 'transparent',
  ghostCheckedHoveredContent: 'communicationBlueTint20',
  ghostCheckedHoveredBorder: 'transparent',

  ghostSecondaryContent: 'iconsSecondary',
  ghostFocusedSecondaryContent: 'iconsSecondary',
  ghostHoveredSecondaryContent: 'iconsSecondary',
  ghostPressedSecondaryContent: 'iconsSecondary',

  brandSecondaryContent: 'iconsSecondary',
  brandFocusedSecondaryContent: 'iconsSecondary',
  brandHoveredSecondaryContent: 'iconsSecondary',
  brandPressedSecondaryContent: 'iconsSecondary',

  buttonDisabledSecondaryContent: 'textSecondary',
  buttonHoveredSecondaryContent: 'iconsSecondary',
  buttonPressedSecondaryContent: 'iconsSecondary',
};
